const express = require('express');
const cors = require('cors');
const routes = require('./routes');
const app = express();

app.use(cors());
app.use(express.json());
app.use(routes);

app.listen(3333);



/*METODOS HTTP
GET: BUSCAR UMA INFORMAÇÃO NO BACKEND
POST: CRIAR UMA INFORMAÇÃO NO BACKEND
PUT: ALTERAR UMA INFORMAÇÃO NO BACKEND
DELETE: DELETAR UMA INFORMAÇÃO NO BACKEND*/

/* TIPOS DE PARAMETROS
QUERY: PARAMETROS NOMEADOS ENVIADOS NA ROTA APOS O SIMBOLO DE INTERROGAÇÃO,
GERALMENTE ELES SERVEM PARA FILTROS.
ROUTE: PARAMETROS UTILIZADOS PARA IDENTIFICAR RECURSOS
request body: CORPO DA REQUISIÇÃO UTILIZADO PARA CRIAR OU ALTERAR RECURSOS*/